### ISSUE TITLE
Allow composition of custom matcher and WireMock's matchers

### ISSUE THREAD

**Issue by zadkiel87** [tomakehurst/wiremock#719] opened 2017-07-19 06:06 UTC
It is not possible to combine a custom matcher and WireMock's matchers in the same mapping. If a custom matcher is present, other matchers are ignored.

Could you add a feature that allows this kind of composition?

Thanks in advance.

**Comment by simonamc** [comment] 2018-03-07 17:15
Looks like a duplicate of #459

**Closed** 2018-11-21 08:50 UTC
Labels: Feature request
