### ISSUE TITLE
How can I obtain values from the JWT to define the request template?

### ISSUE THREAD

**Issue by kwarnke** [tomakehurst/wiremock#685] opened 2017-06-14 19:16 UTC
We are using JWTs in the Authorization header for authenticating with our APIs.

When we mock these APIs, we need to do so under the context of different users which means that we'll have different JWTs where the "sub" claim changes between each request.

Is there a way to parse the JWT to pull the "sub" claim out when defining our request templates?

Thanks!
Kevin

**Comment by tomakehurst** [comment] 2017-07-10 12:37
You might have some luck writing an extension to do this: http://wiremock.org/docs/extending-wiremock/

Closing as this is a question, not a bug/feature request. Please post on the mailing list of you have any further questions.

**Closed by tomakehurst** 2017-07-10 12:37 UTC
