### ISSUE TITLE
never --use-chunked-encoding option is not work

### ISSUE THREAD

**Issue by shimmercn** [tomakehurst/wiremock#1124] opened 2019-05-09 09:46 UTC
**Version** : wiremock-standalone-2.23.2

**Command line** : `java -jar wiremock-standalone-2.23.2.jar --https-port 443 --verbose true --use-chunked-encoding never`

**Mapping file** :
[test.txt](https://github.com/tomakehurst/wiremock/files/3161261/test.txt)

**Response headers** : 
- Content-Type →application/json
- Matched-Stub-Id →d59dc498-bad2-48d9-a8c3-82e055dccc50
- Content-Encoding →gzip
- Vary →Accept-Encoding, User-Agent
- Transfer-Encoding →**chunked**
- Server →Jetty(9.2.z-SNAPSHOT)
---
the --use-chunked-encoding option: never is not work.
I tried adding Content-Length in mapping file,  but Content-Length will disappeared in response headers and return same result like above.

start the server with Java code also has this problem.

**Comment by tomakehurst** [comment] 2019-06-06 19:58
Which HTTP client did you use for this?

I replicated what you've posted here and I'm getting the `Content-Length` header as expected.

**Comment by shimmercn** [comment] 2019-06-07 02:00
The http client is Postman.

Process of my operation is in the gif. The content of test.json is the same as test.txt.

![2019-06-07 09-43-14 2019-06-07 09_46_54](https://user-images.githubusercontent.com/31005752/59076810-807f1080-890a-11e9-9acc-6efe10158529.gif)

**Comment by joranb** [comment] 2019-06-21 07:55
I got the same issue, but i noticed when I call the __admin endpoint where I can see all my stubs the Content-Length header is present, but not when I call that specific endpoint directly.

**Comment by tomakehurst** [comment] 2019-06-21 10:32
The problem is when using gzip with the jre7 version of WireMock, as there's a bug with Jetty's gzip filter.

If you upgrade to the jre8 version of WireMock you should start getting `Content-Length` in the response.

**Comment by joranb** [comment] 2019-06-21 14:32
I tried to clone the repo and build my own version like this: `./gradlew -c release-settings.gradle :java8:shadowJar`
The result was this: wiremock-jre8-standalone-2.24.0.jar
Tried to run it but same result.

**Comment by tomakehurst** [comment] 2019-06-21 19:42
I'd suggest downloading a release, rather than building from master:
https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/2.23.2/wiremock-jre8-standalone-2.23.2.jar

If you could post some specifics about how you've set this up and the request and response you got, that'd be much appreciated.

**Comment by tomakehurst** [comment] 2019-06-21 19:44
I've just retested against 2.23.2-jre8 with Postman, and I'm getting the `Content-Length` header back as expected.

**Comment by joranb** [comment] 2019-06-25 10:54
It turns out to be an issue with gzip in my case, we built our own version of Wiremock with a little tweak and got the content length header. It's a pretty special use case since one of our components doesn't exactly follow best practice when it comes to using the Content-Length header. So this was not a part of this bug. We should definitively fix it sometime, so we could use a release of Wiremock, but right now it was easier for us to modify Wiremock. Thanks for the help!

**Comment by tomakehurst** [comment] 2019-06-25 11:41
OK, in that case I'll close this. Please open a new issue with a test case for reproduction if you find any other scenarios in which this doesn't work as expected (other than the JDK7 version, which is a "won't fix").

**Closed by tomakehurst** 2019-06-25 11:41 UTC
