### ISSUE TITLE
Spring Web-Client reading JSON from Wiremock (newer than 2.17) sometimes freezes

### ISSUE THREAD

**Issue by frzme** [tomakehurst/wiremock#1084] opened 2019-02-20 12:45 UTC
Using WireMock 2.21 (2.18-2.21 seem to be affected) when repeatedely sending http requests which request and decode JSON using the spring WebClient to WireMock the requests sometimes freezes and fail to reply. 
The issue does not occur when using Wiremock 2.17 and it does not occur when requesting Strings (and not decoding JSON).
I'm not entirely certain whether this is a WireMock or a Spring WebClient issue, I'm therefore raising this issue with both projects.

The failing test setup can be found here: https://github.com/FrzMe/wiremock-spring-webclient-block/blob/master/src/test/java/webclientblock/WebClientBlockTest.java#L49

Reasons why it could be a spring issue:

* when requesting "String" via the WebClient the issue does not occur (-> it occurs only when json decoding)   (see https://github.com/FrzMe/wiremock-spring-webclient-block/blob/master/src/test/java/webclientblock/WebClientBlockTest.java#L102)

Reasons why it could be a WireMock issue:

* when requesting from other sources (local nginx, other spring service, etc.) the issue does not occur.
* the issue does not occur in WireMock 2.17

The Issue can be reproduced when running the WebClientBlockTest from https://github.com/FrzMe/wiremock-spring-webclient-block - there the test testWiremockServiceGetJsonDecode fails consistently for me (no later than ~8000 iterations - sometimes much earlier) 
The test also shows that the same problem can not be reproduced when making http requests using the spring RestTemplate.

Both WireMock and WebClient are set up completely self contained within the test.

**Comment by tomakehurst** [comment] 2019-02-20 13:33
Thanks for posting your test project (so much easier than trying to create one from a description!).

I've run the test case with tcpdump enabled and learned the following things:
1) WireMock *is* returning a response over the network in the failure cases (in < 1ms usually)
2) The problem always (based on the samples I've looked at) seems to occur on the *last* use of a pooled client connection before it is closed by the client.

I don't have any firm conclusions to draw from this, but one hypothesis is that there's a race condition inside the client between content retrieval and connection cleanup. I believe the client may be source of this as a) it initiates closure of the connection, not the server, and b) the response is being put on the wire by WireMock.

As for why it works OK with WireMock 2.17, this could be that the version of Jetty has subtly different timing during the hangup protocol.

**Comment by joakime** [comment] 2019-03-12 14:32
Not able to reproduce the reported issue on OSX with OpenJDK 11.0.2
All tests pass with each run.

**Comment by tomakehurst** [comment] 2021-04-28 11:23
Closing as I think this is the issue that was ultimately down to the Netty bug referenced in netty/netty#8922, which is now fixed

**Closed by tomakehurst** 2021-04-28 11:23 UTC
