### ISSUE TITLE
Adding more tests with Rule eventually causes stubFor() to fail

### ISSUE THREAD

**Issue by CodeFarmer** [tomakehurst/wiremock#346] opened 2016-01-15 16:59 UTC
Apologies for the slight vagueness of what is to come - the behaviour we see only happens when running a whole, large, test suite (individual tests work fine) above a certain size, which seems to differ slightly between machines. For what it's worth this is a mostly Mac OSX shop.

Our rules use auto-port allocation. Attempts to hack our own port allocation schemes together (like http://stackoverflow.com/questions/25857164/wiremock-unit-test-failing-locally-java-net-bindexception-address-already-in ) do not help.

We've had this happen previously and it went away when we upgraded to the 2.0 betas (and may in fact be a Jetty issue, as described in another Wiremock issues entry about something similar), but it's back and will not die this time. It's worth repeating: the test cases still work fine when run independently, with mvn -Dtest=whatever or from an IDE. Something cumulative is going on.

We have a mixture of WireMockRule and WireMockClassRule rules in our tests, but at the point where I am now, it does not matter which one the new test uses. The stack traces all look like this (socket closed exception in HttpAdminClient.postJsonAssertOkAndReturnBody()):

unparseableErrorThrowsOriginalException(co.tmol.web.client.phimple.ErrorParsingRestClientTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAssertOkAndReturnBody(HttpAdminClient.java:163)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:81)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:163)
	at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:159)
	at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:82)
	at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:86)
	at co.tmol.web.client.phimple.ErrorParsingRestClientTest.stubSimpleErrorMessageWith500(ErrorParsingRestClientTest.java:32)
	at co.tmol.web.client.phimple.ErrorParsingRestClientTest.unparseableErrorThrowsOriginalException(ErrorParsingRestClientTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

This feels like a Jetty issue somehow, but I am very stuck.

**Comment by CodeFarmer** [comment] 2016-01-15 18:51
Further: Building on Linux gives similar behaviour (effectively the same tests are failing), but a different error message:

happyPathParsesResponseObject(co.tmol.web.client.phimple.BasicRestClientTest)  Time elapsed: 0.033 sec  <<< ERROR!
org.apache.http.conn.HttpHostConnectException: Connect to localhost:58009 [localhost/127.0.0.1, localhost/127.0.1.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.github.tomakehurst.wiremock.client.HttpAdminClient.postJsonAssertOkAndReturnBody(HttpAdminClient.java:163)

...

**Comment by CodeFarmer** [comment] 2016-01-18 12:11
Have tried to run on Linux - same failures on the same tests, with slightly different error messages (conx refused rather than socket closed). This makes me think it's not just running out of file descriptors or something, rather something is going on in Jetty.

**Comment by CodeFarmer** [comment] 2016-04-26 20:41
:tumbleweed:

**Comment by javapapo** [comment] 2016-04-26 20:51
+1

**Comment by adilfulara** [comment] 2016-04-26 20:53
+1

**Comment by tomakehurst** [comment] 2016-04-27 14:26
Is this the case with version 2.x or 1.x (or both)?

**Comment by javapapo** [comment] 2016-04-27 15:19
2.0.8-beta here

**Comment by tomakehurst** [comment] 2016-04-27 15:24
OK, this isn't something I've seen before, so if I'm going to fix it I'll need a bit more info. I realise this may not be that easy, but could you post some code that will (reasonably) reliably replicate this?

In the interim, how are you managing WireMock instances? Are you new'ing up a WireMockServer instance/the rule, or talking to an external instance?

If the former, is switching to the direct version of the DSL an option i.e. calling ``wireMockServer.stubFor(...)``?

**Comment by CodeFarmer** [comment] 2016-04-28 12:54
Hey Tom,

I definitely can't give you my project that is having the problem for reals, but I'm going to spend some time this weekend knocking together a toy one to see if I can demonstrate it from scratch.

In the meantime, the real solution is to get my team to not write so many damn WireMock tests for things that maybe should be mocking any one of the intermediate layers between HTTP and their code instead :P

**Comment by tomakehurst** [comment] 2016-04-28 13:03
Actually, rather than moving it externally, I'd suggest using the rule to call the DSL as this calls directly rather than via HTTP (which the static DSL always does). Since you're seeing exceptions when configuring stubs, this might solve the problem.

**Comment by CodeFarmer** [comment] 2016-04-28 13:31
Interesting, and entirely plausible. Will have a play and get back to you!

**Comment by CodeFarmer** [comment] 2016-06-02 13:43
Content-free update: I haven't been able to replicate it from scratch simply by building thousands of stubs using the HTTP Admin Client, or by generating thousands of test classes from templates.

The project that was having the problem has been reorganised and stopped seeing it (as far as I am aware). So this is not pressing right at this second, but it's annoying me that I can't make it happen now.

**Comment by tomakehurst** [comment] 2016-06-02 13:45
I feel your pain. Absolutely the worst kind of problem. Shall we close this issue for now and reopen if we find the smoking gun?

**Comment by CodeFarmer** [comment] 2016-10-17 16:04
Seems fair to me. I know it's lurking somewhere, and it's real across different OS platforms but... *sigh*

**Closed** 2016-10-17 16:24 UTC

**Comment by michel-kraemer** [comment] 2019-06-22 11:56
I had the same problem in https://github.com/michel-kraemer/gradle-download-task. I can confirm 
that switching to the direct version (`wireMockServer.stubFor(...)`) works. Thank you!
