### ISSUE TITLE
match method returns wrong result when compare two empty json arrays

### ISSUE THREAD

**Issue by SeverinP** [tomakehurst/wiremock#1028] opened 2018-11-02 13:27 UTC
I have a mismatch for a request with body expected to be [] in JSON. I found that match method of EqualToJsonPattern returns wrong result when compares [] and [].

In code :

double maxNodes = maxDeepSize(expected, actual);
return diffSize(diff) / maxNodes;

maxNodes will be o and it will cause return result to be NaN. 
And NaN affects the match result to be wrong.

https://github.com/tomakehurst/wiremock/blob/b8c89542c24dc9c2782039705411bb53bc77a6f5/src/main/java/com/github/tomakehurst/wiremock/matching/EqualToJsonPattern.java#L116

**Comment by tomakehurst** [comment] 2018-11-02 13:47
I'm not sure I understand what you're saying here.

1) Is this a duplicate of #632 ?
2) If not, can you provide a test case that demonstrates the issue?

**Comment by tomakehurst** [comment] 2019-01-04 20:16
Closing, as I believe this to be fixed now by the resolution to #632

**Closed by tomakehurst** 2019-01-04 20:16 UTC
