### ISSUE TITLE
Test hanging with Java 11

### ISSUE THREAD

**Issue by PyvesB** [tomakehurst/wiremock#1009] opened 2018-10-09 16:29 UTC
Hello there,

We've encountered a strange behaviour after upgrading to Java 11. Here's a minimal test to reproduce the issue:
```
@Test
public void testConnectionReset() throws IOException {
    WireMockServer wireMockServer = new WireMockServer(WireMockConfiguration.options().dynamicPort());
    wireMockServer.start();

    try {
        wireMockServer
                .stubFor(get(urlEqualTo("/endpoint")).willReturn(aResponse().withFault(Fault.CONNECTION_RESET_BY_PEER)));

        HttpURLConnection httpURLConnection = (HttpURLConnection) URI.create(wireMockServer.url("/endpoint")).toURL()
                .openConnection();

        assertThrows(SocketException.class, () -> httpURLConnection.getResponseCode());
    } finally {
        wireMockServer.stop();
    }

}
```

Using Java 10, this test passes happily, i.e. the `SocketException` is thrown due to the connection being reset. Nevertheless, in Java 11 it hangs. Here's the log output at the point it's hanging:
```
2018-10-09 17:23:01.723 [      main]               org.eclipse.jetty.util.log I Logging initialized @1491ms
2018-10-09 17:23:01.791 [      main]          org.eclipse.jetty.server.Server I jetty-9.2.24.v20180105
2018-10-09 17:23:01.805 [      main]  o.e.jetty.server.handler.ContextHandler I Started o.e.j.s.ServletContextHandler@7aead3af{/__admin,null,AVAILABLE}
2018-10-09 17:23:01.806 [      main]  o.e.jetty.server.handler.ContextHandler I Started o.e.j.s.ServletContextHandler@4b869331{/,null,AVAILABLE}
2018-10-09 17:23:01.823 [      main]    o.e.j.s.NetworkTrafficServerConnector I Started NetworkTrafficServerConnector@6f20b4e3{HTTP/1.1}{0.0.0.0:53426}
2018-10-09 17:23:01.826 [      main]          org.eclipse.jetty.server.Server I Started @1597ms
2018-10-09 17:23:01.951 [      main]          org.eclipse.jetty.server.Server I jetty-9.2.24.v20180105
2018-10-09 17:23:01.953 [      main]  o.e.jetty.server.handler.ContextHandler I Started o.e.j.s.ServletContextHandler@282ffbf5{/__admin,null,AVAILABLE}
2018-10-09 17:23:01.953 [      main]  o.e.jetty.server.handler.ContextHandler I Started o.e.j.s.ServletContextHandler@45e1aa48{/,null,AVAILABLE}
2018-10-09 17:23:01.954 [      main]    o.e.j.s.NetworkTrafficServerConnector I Started NetworkTrafficServerConnector@12c60152{HTTP/1.1}{0.0.0.0:53427}
2018-10-09 17:23:01.955 [      main]          org.eclipse.jetty.server.Server I Started @1725ms
2018-10-09 17:23:02.020 [2822728-28]                                        / I RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
```

Note that we're using the latest version of Wiremock, 2.19.0, on Mac OSX.

Thanks in advance for your help,

Pyves

**Comment by tomakehurst** [comment] 2018-10-09 16:52
Thanks for reporting this. It seems Java 11 breaks a couple of network related things, which is troubling.

Which version of Java did you upgrade from (i.e. what's the highest working version you're aware of)?

**Comment by tomakehurst** [comment] 2018-10-09 17:48
Sorry, totally missed the fact you said it worked fine in Java 10!

**Comment by tomakehurst** [comment] 2018-10-10 19:32
This looks like it might be a duplicate of #970

**Closed** 2021-05-06 20:00 UTC
Labels: Bug
