### ISSUE TITLE
proxy forwarding using SSL - feature request

### ISSUE THREAD

**Issue by txjohng** [tomakehurst/wiremock#379] opened 2016-03-29 15:10 UTC
First, i apologize if this is not the right place for a request.

Secondly, I know that from a previous threads this is not allowed per design:
https://github.com/tomakehurst/wiremock/issues/62 and https://github.com/tomakehurst/wiremock/issues/139
### Ah, no that's correct - you can't forward proxy onto SSL. This is a general limitation, as the whole point in SSL is preventing man-in-the-middle attacks.

Is there a way to add this?  maybe something like --enable-browser-proxying-with-ssl?  

It would be great to proxy everything from our IIS to it and have to forward all requests to the original endpoint, unless we post an overide for a specific url which WireMock could mock.  Our endpoints are about 50% SSL and about 50% non SSL.

**Comment by tomakehurst** [comment] 2016-03-29 15:24
Unfortunately this is a limitation (by design) of HTTPS, not WireMock specifically. If it were possible to forward proxy HTTPS in a way that made the contents of the request/response visible, it wouldn't be secure.

With WireMock you can reverse proxy onto an HTTPS endpoint, because in that instance you're serving a different SSL cert and domain to the client (i.e. the one you assigned to WM).

**Comment by txjohng** [comment] 2016-03-29 16:40
Are you familiar with Fiddler?  Does, it act as a forward or reverse proxy by default? I ask, because it forwards all calls to their endpoint and acts as a "man in the middle".  It will forward non ssl and ssl to their final endpoint. It can decode ssl if you install a local cert. 

however, wiremock doesn't appear to receive/forward these ssl requests.

this is how I am trying to use WireMock
IIS forwards all outbound request to wiremock.
if wiremock has a rule, it returns the mock. else, it forwards it to the original destination.

**Comment by tomakehurst** [comment] 2016-04-01 10:18
Yeah, it looks like they've managed it somehow with Fiddler, although you end up with an untrusted cert being served back to the browser.

I'm not sure how they get round the fact that browsers issue a CONNECT request when proxying via HTTPS (to initiate a TCP tunnel). I'd like to support this too, so I'll dig a little deeper when I get the chance.

**Comment by txjohng** [comment] 2016-04-01 14:27
Thanks! I really appreciate it. I am not 100% how they do it.  I know both ssl and non ssl traffic flow through the same port and they install a local cert on the machine. http://www.fiddlerbook.com/fiddler/help/httpsdecryption.aspx

i think mock server also does it  - http://www.mock-server.com/proxy/running_mock_server_proxy.html
### To simplify configuration all MockServer versions (except the deployable WAR) only use a single port to support HTTP, HTTPS and SOCKS. This is achieved by dynamically detecting if the client is using HTTP, HTTPS or SOCKS.

There are a few others that also do it, 
mitmproxy, mitm-proxy, paros, charles, burp - but none have the mocking capabilities that wireMock has. And the post feature is incredibly awesome!

**Comment by txjohng** [comment] 2016-05-25 14:28
Hi Tom,   has this been added?  from the looks of it, I think it has been.  My planned usage for this would to run it like fidder forcing all IIS traffic to it and from there it should forward to original endpoint unless we have a rule to mock it.

thanks!

-https-port: If specified, enables HTTPS on the supplied port.

--https-keystore: Path to a keystore file containing an SSL certificate to use with HTTPS. The keystore must have a password of “password”. This option will only work if --https-port is specified. If this option isn’t used WireMock will default to its own self-signed certificate.

--keystore-password: Password to the keystore, if something other than “password”.

--https-truststore: Path to a keystore file containing client certificates. See HTTPS and Proxying to a target server that requires client certificate authentication for details.

--truststore-password: Optional password to the trust store. Defaults to “password” if not specified.

--https-require-client-cert: Force clients to authenticate with a client certificate. See HTTPS for details.

**Comment by tomakehurst** [comment] 2016-05-25 16:53
No, not for forward proxying I'm afraid. A couple of experiments have been attempted, but it's not trivial to do.

**Comment by txjohng** [comment] 2016-05-25 17:52
appreciate the effort!

**Comment by mturcottelog10** [comment] 2016-05-26 16:05
Hey Tom, you're building a really usefull tool here! Your mocking service saved me a lot of time.
But the issue opened by txjohng would help me a lot too. I would greatly appreciate to see this feature.

Thanks!

**Comment by tomakehurst** [comment] 2016-05-27 18:28
I'd also really like this feature :-)

Unfortunately it looks like it's going to take some tinkering to get it working. I believe @rowanhill has already looked at this briefly, and it didn't seem all that straightforward.

**Comment by oneeyedhobbit** [comment] 2016-07-08 21:35
@tomakehurst have you had a chance to look into this more?  I would also find it a valuable addition if it is possible.

**Comment by tomakehurst** [comment] 2016-07-08 22:04
No progress since the last post I'm afraid. Definitely still a high priority, but it's going to take some effort to get it working with Jetty unfortunately.

**Comment by jamesem** [comment] 2016-08-19 19:47
@tomakehurst Chipping in on this subject, this would be the one feature which means I can use WireMock!

My use case is connecting an Android device through WireMock, as they would through other HTTP proxies such as Fiddler or Charles. This way we would like to test and alter responses for live builds, without having to alter them.

Reverse proxying is a no go for this as without forward proxying, the periodic requests Android makes to check for connectivity do not get passed through, among other requests too. Android marks the WiFi connection "Connected, No Internet", and it actively avoids the connection (to WireMock).

On the surface, Fiddler and Charles allow you to specify which hosts they perform MITM attacks on, which is really important so they don't MITM attack every HTTPS connection by default (thereby serve untrusted certs).

**Comment by tomakehurst** [comment] 2016-08-31 11:12
Noted. As I said, I'd really like to do this, but it's going to take some sustained effort to make it work, as unlike Netty, Jetty doesn't have a MITM proxy feature.

If you feel like trying to figure it out yourself I'd be more than happy to accept a PR!

**Comment by reegnz** [comment] 2018-03-09 16:49
The Fiddler project mentioned by @txjohng is a MITM approach, where you need to ensure the self signed cert of Fiddler is trusted: http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/TrustFiddlerRootCert

It's not a bad approach, especially for a controlled test environment.
I believe the simplest approach would be to:
1. Always generate the root certificate on startup (or have it be configurable)
2. Take the java trust store + the self signed cert and create a new trust store from them
3. Configure the clients used from the tests to trust the root certificate

Step 3 could be as simple as setting the javax.net.ssl.trustStore system property to a file generated in no2.

As an alternative to a trust store, you could also just create a custom TrustManager that accepts anything during the test run.

https://github.com/ganskef/LittleProxy-mitm is a potential solution that IMHO is a solution that's already out there, just waiting to be integrated.
It takes the same approach as mitmproxy.

Some example I saw on how other projects do this:
https://github.com/betamaxteam/betamax/blob/6e14f5edc53d46ef83f41115da21971e2389e443/betamax-core/src/main/java/software/betamax/proxy/ProxyServer.java#L91

**Comment by reegnz** [comment] 2018-03-09 16:53
I also suggest reading this: https://corte.si/posts/code/mitmproxy/howitworks/index.html
It describes in detail how [mitmproxy](https://mitmproxy.org/) works, and it's a great read to get to know such concepts as MITM interception and forging server responses.
Only thing you have to ensure is that the client trusts your root cert.

**Comment by reegnz** [comment] 2018-03-09 17:06
#379 seems to be a related issue.

**Comment by tomakehurst** [comment] 2018-03-09 17:15
Or the same issue :-)

**Comment by tomakehurst** [comment] 2018-03-09 17:16
I looked at LittleProxy a while back. I think it could probably be made to work, my only reservation is how much extra runtime footprint it would add, and how much bigger the fat JAR would get.

Do you feel like giving it a try and raising a PR?

**Comment by jineshqa** [comment] 2019-08-09 16:36
@tomakehurst  Any updates on this one? This feature will make wiremock a darling of even haters.

**Comment by tomakehurst** [comment] 2019-08-09 17:04
I'm afraid not. I'd love to work on this, but it's quite a big one and I just don't have the capacity at the moment.

**Comment by jineshqa** [comment] 2019-08-10 17:02
Thanks for prompt reply.

**Comment by devansh-dalal** [comment] 2020-11-20 17:07
@tomakehurst, Thanks for the awesome work you guys have been doing. Have anyone happened to take any stabs at this?

**Comment by tomakehurst** [comment] 2020-11-20 17:46
Yeah, it's in the latest version as it happens: http://wiremock.org/docs/proxying/#browser-proxying-of-https.

Closing this, as I ought to have after the release....

**Closed by tomakehurst** 2020-11-20 17:46 UTC
Labels: Feature request

**Comment by devansh-dalal** [comment] 2020-11-23 03:34
thanks, 1 more q. Will it be a version > `2.27.2`?

**Comment by tomakehurst** [comment] 2020-11-23 11:33
It's been there since 2.27.0 and I'm not planning to remove it, so yes

**Comment by devansh-dalal** [comment] 2021-01-05 13:02
Hey @tomakehurst ,

The test(`webclientWithWireMockAsProxyServer `) mentioned in https://github.com/reactor/reactor-netty/issues/617 still fails for this combination `wiremock` + `netty-client` + `http`. Meaning even when I am trying to get via `http` resource, it fails. I will be very thankful if you could explain, what is the issue here.
