### ISSUE TITLE
IllegalArgumentException: resource keystore not found (fix included)

### ISSUE THREAD

**Issue by m2kk** [tomakehurst/wiremock#815] opened 2017-11-21 11:49 UTC
Hey guys,

we experiences some issue on integrating this library to an android project.
We got this exception and looked into it, and also found the solution.
`Caused by: java.lang.IllegalArgumentException: resource keystore not found.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
    at com.google.common.io.Resources.getResource(Resources.java:197)`

One time it occurs at:
WireMockConfiguration:62 -> 
`private String keyStorePath = Resources.getResource("keystore").toString();`
Solution:
`private String keyStorePath = getClass().getClassLoader().getResource("keystore").toString();`

Another time, (actually never crashed there, but found by searching other occurances:
Problem: HttpSettings.Builder: 101 ->
`private String keyStorePath = Resources.getResource("keystore").toString();`
Solution, same as above:
`private String keyStorePath = getClass().getClassLoader().getResource("keystore").toString();`

Fix works without any flaws.
Searched a lot about it on the net, seems to be some packaging issue if you integrate the library, the file cannot be found within the library space.

Would be very gerat if this fix could be applied anytime soon.

**Comment by cdilks** [comment] 2019-04-21 15:28
I'm seeing this crash in another place
Stacktrace:
`Caused by: java.lang.IllegalArgumentException: resource assets not found.
	at wiremock.com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at wiremock.com.google.common.io.Resources.getResource(Resources.java:197)
	at com.github.tomakehurst.wiremock.jetty9.JettyHttpServer.addAdminContext(JettyHttpServer.java:389)` 
The line that seems to be the culprit:
`adminContext.setInitParameter("org.eclipse.jetty.servlet.Default.resourceBase", Resources.getResource("assets").toString());`
The proposed fix:
`adminContext.setInitParameter("org.eclipse.jetty.servlet.Default.resourceBase", getClass().getClassLoader().getResource("assets").toString());`

This is assuming the fix that worked above works here as well. It seems as though its the same problem.

**Comment by ViToni** [comment] 2019-06-08 15:48
Seems I have a similar issue
```
java.lang.IllegalArgumentException: resource keystore not found.
	at wiremock.com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at wiremock.com.google.common.io.Resources.getResource(Resources.java:197)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.<init>(WireMockConfiguration.java:58)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig(WireMockConfiguration.java:104)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration$wireMockConfig.callStatic(Unknown Source)
	at com.qivicon.runtime.test.HttpMockOSGiTest.startMockServer(HttpMockOSGiTest.groovy:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at aQute.junit.Activator.test(Activator.java:340)
	at aQute.junit.Activator.run(Activator.java:186)
	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1405)
	at aQute.launcher.Launcher.runWithoutInit(Launcher.java:370)
	at aQute.launcher.Launcher.run(Launcher.java:317)
	at aQute.launcher.Launcher.main(Launcher.java:122)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:147)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:112)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:47)

java.lang.NullPointerException: Cannot invoke method stop() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
```

**Comment by ViToni** [comment] 2019-06-13 09:59
Seems I have a similar issue
```
java.lang.IllegalArgumentException: resource keystore not found.
	at wiremock.com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
	at wiremock.com.google.common.io.Resources.getResource(Resources.java:197)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.<init>(WireMockConfiguration.java:58)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig(WireMockConfiguration.java:104)
	at com.github.tomakehurst.wiremock.core.WireMockConfiguration$wireMockConfig.callStatic(Unknown Source)
	at com.acme.test.HttpMockOSGiTest.startMockServer(HttpMockOSGiTest.groovy:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at aQute.junit.Activator.test(Activator.java:340)
	at aQute.junit.Activator.run(Activator.java:186)
	at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1405)
	at aQute.launcher.Launcher.runWithoutInit(Launcher.java:370)
	at aQute.launcher.Launcher.run(Launcher.java:317)
	at aQute.launcher.Launcher.main(Launcher.java:122)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:147)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:112)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:47)
```

**Comment by othmanelkourd** [comment] 2019-11-27 14:00
Hey Guys, 
the issue is fixed for me after updating wiremock version to **2.25.1**
I don't know exactly what was the exact thing that fixed the keystore issue. 
Regards

**Comment by tomakehurst** [comment] 2021-04-28 09:23
Closing this for now as I'm planning to properly address Android compatibility in 3.x

**Closed by tomakehurst** 2021-04-28 09:23 UTC

**Comment by NitinAtGitHub** [comment] 2022-09-07 12:38
I am getting Constructor below exception 

Failed to instantiate [***********************************.DefaultWireMockManager]
threw exception; nested exception is java.lang.IllegalArgumentException: resource keystore not found.

So , do I need to continue with below change or do we have another solution to it 

WireMockConfiguration:62 ->
private String keyStorePath = Resources.getResource("keystore").toString();
Solution:
private String keyStorePath = getClass().getClassLoader().getResource("keystore").toString();
