### ISSUE TITLE
Wiremock json file stub behavior is not understandable

### ISSUE THREAD

**Issue by heart4hackers** [tomakehurst/wiremock#1016] opened 2018-10-23 14:23 UTC
Hi guys,

currently I use wiremock version:
```xml
<dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <version>2.19.0</version>
        </dependency>
        
I do start my wiremock server via Java like this:

```java

 private WireMockServer wiremock = new WireMockServer(
            wireMockConfig()
                    .port(10302)
            .usingFilesUnderDirectory("target/classes/mocks/mappings/my-directory")

    );

```

When i configure wiremock to run with that confugration:
```json
{
mappings: [
{
id: "6fef57f6-ba86-4daf-a553-69d947e2c214",
request: {
method: "ANY"
},
response: {
status: 200,
body: "{"orders":true}"
},
uuid: "6fef57f6-ba86-4daf-a553-69d947e2c214"
},
{
id: "5868b5ba-f0bc-4b21-b8e4-16a669e3afec",
request: {
method: "ANY"
},
response: {
status: 200,
body: "{"lines":true}"
},
uuid: "5868b5ba-f0bc-4b21-b8e4-16a669e3afec"
},
{
id: "b9f1b651-d2b8-4c4d-b0b8-2f413d2168f4",
request: {
urlPath: "/hello/2",
method: "GET"
},
response: {
status: 200,
bodyFileName: "orders/39d52f7b-bfe8-4d68-aa80-89094de6157a.json"
},
uuid: "b9f1b651-d2b8-4c4d-b0b8-2f413d2168f4"
},
{
id: "f6689b53-a28b-4d27-84a3-d2ce61638759",
request: {
urlPath: "/hello/1",
method: "GET"
},
response: {
status: 200,
bodyFileName: "lines/39d52f7b-bfe8-4d68-aa80-89094de6157a.json"
},
uuid: "f6689b53-a28b-4d27-84a3-d2ce61638759"
}
],
meta: {
total: 4
}
}


```

The result ist always on /hello/1 or /hello/2 {orders: true} but this is wrong.

I expect for /hello/1 
{lines: true}

and for /hello/2
{orders: true}

For me it looks like a bug but maybe I am doing something wrong.

**Comment by heart4hackers** [comment] 2018-10-23 14:45
Can be closed, found the bug. If you load files from a sub folder from mappings folder, it will load the responses as "new stubs". Misleading behavior not documented.

**Comment by tomakehurst** [comment] 2018-10-23 14:47
The problem is that some of your stubs don't have a URL matcher of any kind in the request part. This means they will match any URL.

The best approach is usually to make your stubs quite specific and non-overlapping, or if you want the first two stubs to be defaults when the ones with URLs don't match, add priority:10 to them.

Closing since this isn't a bug. Please post further questions to the mailing list.

**Closed by tomakehurst** 2018-10-23 14:47 UTC

**Comment by heart4hackers** [comment] 2018-10-23 14:48
Okay, new problem:
com.github.tomakehurst.wiremock.security.NotAuthorisedException: Access to file ../lines/d145c568-d10d-44c5-ad15-1ff0b57749fa.json is not permitted

So I am not allowed to put stub responses in same directory with mappings, and when i put the stub responses in an other directory it's also not possible. No idea how to solve this.
