### ISSUE TITLE
RuntimeException when caller's connection is closed before wiremock delayed response

### ISSUE THREAD

**Issue by vnikolov** [tomakehurst/wiremock#361] opened 2016-02-10 18:36 UTC
To reproduce the delay exception problem you don't need httpclient at all.

The same problem occurs with Postman or any other client. Here are the steps to reproduce:

1. Post to http://localhost:8089/__admin/mappings/new
{
    "request": {
        "method": "GET",
        "urlPattern": "/mock/timeout"
    },
    "response": {
        "status": 200,
        "fixedDelayMilliseconds": 6000,
        "body": "Timeout"
    }
}

2. Get http://localhost:8089/mock/timeout

3. After 2-3 seconds (while Postman is still waiting for the response) hit Reset this tab (or close Postman)

Result in WireMock console:

2016-02-09 15:23:49.285 /mock/timeout
- hide quoted text -
java.lang.RuntimeException: wiremock.org.mortbay.jetty.EofException
        at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.writeAndTranslateExceptions(Jetty6HandlerDispatchingServlet.java:134)
        at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.applyResponse(Jetty6HandlerDispatchingServlet.java:124)
        at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.service(Jetty6HandlerDispatchingServlet.java:103)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at wiremock.org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at wiremock.org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at wiremock.org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at wiremock.org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at wiremock.org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at wiremock.org.mortbay.jetty.Server.handle(Server.java:326)
        at wiremock.org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at wiremock.org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at wiremock.org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at wiremock.org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at wiremock.org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at wiremock.org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at com.github.tomakehurst.wiremock.jetty6.DelayableSocketConnector$1.run(DelayableSocketConnector.java:49)
        at wiremock.org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: wiremock.org.mortbay.jetty.EofException
        at wiremock.org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:791)
        at wiremock.org.mortbay.jetty.AbstractGenerator$Output.flush(AbstractGenerator.java:569)
        at wiremock.org.mortbay.jetty.HttpConnection$Output.flush(HttpConnection.java:1012)
        at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServlet.writeAndTranslateExceptions(Jetty6HandlerDispatchingServlet.java:131)
        ... 17 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at wiremock.org.mortbay.io.ByteArrayBuffer.writeTo(ByteArrayBuffer.java:368)
        at wiremock.org.mortbay.io.bio.StreamEndPoint.flush(StreamEndPoint.java:129)
        at wiremock.org.mortbay.io.bio.StreamEndPoint.flush(StreamEndPoint.java:161)
        at wiremock.org.mortbay.jetty.HttpGenerator.flush(HttpGenerator.java:714)
        ... 20 more

Notes: 
This happens ONLY if there is a body specified. If there is no body it's all good.
The problem is for both GET and POST.
It takes about one more second after the connection is closed for the exception to show.

**Comment by nikolavp** [comment] 2016-02-11 12:02
+1 on this one. I was observing it on several occasions but couldn't catch the cause.

**Comment by tomakehurst** [comment] 2016-02-11 12:54
Can you confirm you're seeing the same behaviour in 2.x?

If not, I'm going to close this as we're not doing any more work on 1.x.

**Comment by vnikolov** [comment] 2016-02-11 19:50
2.x is ok, the issue does not exist there.

**Closed** 2016-07-27 13:04 UTC

**Comment by mitchell1972** [comment] 2017-04-21 23:28
java.lang.NoSuchMethodError: org.mortbay.jetty.handler.ContextHandler.<init>(Lorg/mortbay/jetty/handler/ContextHandler$SContext;)V

I keep getting the above error when running my BDD test from the runner file - any ideas what I'm doing wrong?
