### ISSUE TITLE
Wrong matching with urlPathEqualTo?

### ISSUE THREAD

**Issue by sartymlg** [tomakehurst/wiremock#323] opened 2015-11-13 10:53 UTC
Hi, I don't sure if is the expected behaviour, In this case the request matches but the request's url is different from the stub (only shares the prefix)

Setting only this expectation:
```
 stubFor(get(urlPathEqualTo("/fixedpath"))
                .willReturn(aResponse()
                .withStatus(205)
```
This call
```
javax.ws.rs.client.ClientBuilder.newClient().target("http://localhost:8080").restClient.path("/fixedpathEmptyBody").request().get()
```
returns 205 instead 404

Is it the expected behaviour or is a bug?

**Comment by tomakehurst** [comment] 2015-11-13 11:21
I'd say that's a bug. Thanks for reporting.

**Comment by SNeugber** [comment] 2015-12-07 11:51
There is a test in wiremock\src\test\java\com\github\tomakehurst\wiremock\VerificationAcceptanceTest.java, which seems to suggest this is the intended behaviour:

        @Test
        public void verifiesRequestBasedOnUrlPathOnly() {
            testClient.get("/this/got/requested");
            verify(getRequestedFor(urlPathEqualTo("/this/got")));
        }

Can you confirm whether this is the case or not?

**Comment by tomakehurst** [comment] 2015-12-07 13:02
This is wrong, and I'm really not sure what I was thinking when I wrote it. I've fixed this on an as yet unpushed change, so it'll be fixed in the next beta release.

**Comment by tomakehurst** [comment] 2015-12-19 14:39
Fixed in 2.0.8-beta

**Closed by tomakehurst** 2015-12-19 14:39 UTC

**Comment by sartymlg** [comment] 2016-01-12 08:35
Thanks for fix the bug, I think this bug is important, please, could you include the fix in the stable version 1.x?

**Comment by tomakehurst** [comment] 2016-01-12 10:13
We're not planning to change the 1.x branch now. However 2.0 beta is very stable and close to going GA so I suggest you use this if you need this fix.
