### ISSUE TITLE
WireMockClient.verifyThat accesses wrong wireMockClient instance on port 8080

### ISSUE THREAD

**Issue by mathume** [tomakehurst/wiremock#607] opened 2017-02-14 11:35 UTC
I use wiremock client to match against a wiremock server instance in a non-junit test.
As my match fails, it tries to load near matches, but
`WireMock.findNearMissesFor` accesses `defaultInstance.get()` which has `.port==8080` instead of accessing `WireMock.admin`.
Therefore I receive the exception `"org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)"` in my test code, which is wrong.

**Comment by tomakehurst** [comment] 2017-02-28 21:51
Hmmm...thought I'd got this fixed. Any chance you could supply a test case?

Also, presume you're on v2.5.1?

Thanks.

**Comment by tomikaa87** [comment] 2019-02-18 16:02
Hi,

Any updates on this? We've ran into the same issue. Our WireMock server is running on an AWS instance, and the tests which are trying to access it are running on a different server, so unfortunately this bug renders this library unusable.

**Comment by tomakehurst** [comment] 2019-02-19 07:22
@tomikaa87 can you supply some details of the problem (incl. stack trace) you're seeing + the version you're running and your setup?

**Comment by tomikaa87** [comment] 2019-02-19 08:47
We use 2.21.0 of wiremock-jre8.

The error occurs in the following stack trace:

```<init>:22, WireMockBuilder (com.github.tomakehurst.wiremock.client)
create:70, WireMock (com.github.tomakehurst.wiremock.client)
initialValue:65, WireMock$1 (com.github.tomakehurst.wiremock.client)
initialValue:62, WireMock$1 (com.github.tomakehurst.wiremock.client)
setInitialValue:180, ThreadLocal (java.lang)
get:170, ThreadLocal (java.lang)
givenThat:106, WireMock (com.github.tomakehurst.wiremock.client)
stubFor:110, WireMock (com.github.tomakehurst.wiremock.client)```

The issue is that `givenThat()` executes `.register(mappingBuilder);`, which is always called on the default instance, and register will try to communicate to the server on the default address. In case of a locally executed test, this works fine, but when the WireMock server is running on a remote instance, it will fail to connect to it. We could work around this issue by calling `stubFor()` which only creates the StubMapping, but doesn't call `register()`. 

In my opinion, if the default instance could be replaced after constructing the first WireMock instance, it could fix the issue. (Or none of the static member functions on the API should not make calls to the WireMock server)

**Comment by tomakehurst** [comment] 2019-02-19 09:03
So can you post your setup code?

**Comment by tomakehurst** [comment] 2019-02-19 09:13
I'm guessing you're using a test timeout or something that puts the test onto a different thread than your setup code?

This is a bit broken WRT the static DSL, but you can work around this by creating an instance of `WireMock` instead.

**Comment by tomikaa87** [comment] 2019-02-19 09:57
This was the original setup code for one of the mappings:

```
        ResponseDefinitionBuilder response =
                WireMock.aResponse()
                        .withBody("{ \"result\": { \"tokenStatus\": \"" + tokenStatus + "\", \"requestId\": \"{{request.requestLine.query.requestId}}\" } }")
                        .withHeader("Content-Type", "application/json");

        StubMapping mapping = WireMock.stubFor(WireMock.get(WireMock.urlPathEqualTo("<mapping path comes here>"))
                .withMetadata(Metadata.metadata().attr("sessionId", sessionId))
                .willReturn(response)
                .withQueryParam("token", WireMock.equalTo(token))
                .atPriority(1000)
        );

        wireMock.register(mapping);
```

The test runs only on a single thread, I've checked if we call WireMock from multiple ones, but we don't.

**Comment by tomakehurst** [comment] 2019-02-19 11:11
The stack trace you posted is for the static DSL, but the code is using an instance. There seems to be a disconnect here.

Are you using the static DSL for your verification calls?

**Comment by tomikaa87** [comment] 2019-02-19 11:34
We use the instance for registering the mapping, but we also use a few static call to create patterns, like `WireMock.urlPathEqualTo`.

**Comment by tomakehurst** [comment] 2019-02-19 11:37
Are you calling WireMock.configureFor() to set the static DSL host and port?

**Comment by tomikaa87** [comment] 2019-02-19 11:42
Ok then, it seems to be a user error in this case. I didn't realize that this should be called as well, but it wasn't clear that one must setup the static instance as well if there is another instance.

**Comment by tomakehurst** [comment] 2019-02-19 19:46
Correction - works perfectly fine with multithreaded tests since 6045de537c7dbc76b23e6a93829222a30735a11d

**Comment by tomakehurst** [comment] 2019-02-19 19:47
Don't think this is a bug any more, so closing

**Closed by tomakehurst** 2019-02-19 19:47 UTC
Labels: Bug

**Comment by LeonorLunatech** [comment] 2020-06-18 07:57
This extra setup `WireMock.configureFor(server.port())` that is needed in order to have the `verify` working is really not clear in the documentation `http://wiremock.org/docs/verifying/`
I had something running on port 8080, so my error was different initially. When I got an error related with port 8080 I got even more confused.

**Comment by tomakehurst** [comment] 2020-06-18 09:13
@LeonorLunatech http://wiremock.org/docs/getting-started/#non-junit-and-general-java-usage
