### ISSUE TITLE
How I can create  wiremock server  in Andriod platform?

### ISSUE THREAD

**Issue by flyfeihuang** [tomakehurst/wiremock#252] opened 2015-03-18 12:34 UTC
Recently,I want to test HTTP request/response for a Andriod App .So, I don't want create a -wiremock stanalone in my PC,and gradle it to Android program in Anriod Studio.However,I meet a lot trouble on it.

This is my part of build.gradle:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile ('com.github.tomakehurst:wiremock:1.54')
            {
                exclude group: 'org.json', module: 'json'
                exclude group:'org.apache.httpcomponents',module:'httpclient'
                exclude group:'org.mortbay.jetty',module:'jetty'
                exclude group:'com.google.guava',module:'guava'
                exclude group:'com.fasterxml.jackson.core',module:'jackson-core'
                exclude group:'com.fasterxml.jackson.core',module:"jackson-annotations"
                exclude group:'com.fasterxml.jackson.core',module:'jackson-databind'
                exclude group: 'org.json', module: 'json'
                exclude group:'org.skyscreamer',module:'jsonassert'
                exclude group:'xmlunit',module:'xmlunit'
                exclude group:'com.jayway.jsonpath',module:'json-path'
                exclude group:'net.sf.jopt-simple',module:'jopt-simple'
                exclude group:'org.apache.httpcomponents',module:'httpclient'

            }
}

exception:03-18 20:23:12.908  28398-28398/com.example.administrator.hellowworld E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.administrator.hellowworld, PID: 28398
    java.lang.NoClassDefFoundError: org.apache.http.impl.client.HttpClientBuilder
            at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:45)
            at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:91)
            at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:95)
            at com.github.tomakehurst.wiremock.http.HttpClientFactory.createClient(HttpClientFactory.java:99)
            at com.github.tomakehurst.wiremock.client.HttpAdminClient.<init>(HttpAdminClient.java:56)
            at com.github.tomakehurst.wiremock.client.HttpAdminClient.<init>(HttpAdminClient.java:60)
            at com.github.tomakehurst.wiremock.client.WireMock.<init>(WireMock.java:61)
            at com.github.tomakehurst.wiremock.client.WireMock.<clinit>(WireMock.java:42)
            at com.example.administrator.hellowworld.MainActivity.<init>(MainActivity.java:16)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1215)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2263)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2398)
            at android.app.ActivityThread.access$800(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5367)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
            at dalvik.system.NativeStart.main(Native Method)

Who can help me?Thank you very much!

**Comment by juhlila** [comment] 2015-08-13 18:22
+1 
I'd like to know that too

**Comment by tomakehurst** [comment] 2015-08-15 11:34
Unfortunately it's not straightforward as there are some libraries used by WireMock that aren't compatible with Android. I'm slowly refactoring the project so that all the platform specific stuff is separate from the generic, which should pave the way to an Android build. Apologies that this doesn't help you very much at the moment.

**Comment by yogurtearl** [comment] 2015-09-07 19:12
Dropping Java 6 support will make it hard/impossible to run Wiremock on Android. :(
Will everything that needs Java 7+ be pluggable, so I can swap in implementations with Java 6 supported stuff? 

Also, if you are just looking for modern language features you could use Kotlin as an implementation language. It has explicit Android support. http://kotlinlang.org/

**Comment by tomakehurst** [comment] 2015-09-08 08:00
Mind if we have this discussion on the mailing list thread?

**Comment by cdewangan** [comment] 2015-10-15 00:18
+1 for this support, I also tried pointing my Android app to WireMock but its not working. Please let me know if someone had successful implementation. 

I will be good with emulator also.

**Comment by handstandsam** [comment] 2016-01-06 03:16
@flyfeihuang @juhlila @cdewangan
### Android support is now available with 2.0.8-beta! ###

See the [Android Support Github issue] (https://github.com/tomakehurst/wiremock/issues/53) for how to set this up.

This issue can be marked as a duplicate of the Android Support issue, https://github.com/tomakehurst/wiremock/issues/53.

**Comment by tomakehurst** [comment] 2016-01-12 14:23
Agreed. Closing as duplicate of #53

**Closed by tomakehurst** 2016-01-12 14:23 UTC
