### ISSUE TITLE
Match request on bodyPattern with response fixed delay greater than 30000ms gives 404 

### ISSUE THREAD

**Issue by samlatham** [tomakehurst/wiremock#1026] opened 2018-10-31 22:53 UTC
Using WireMock version 2.19.0 standalone

As per the title.... I've created a mapping like so... 

`{
  "id": "cb7872bd-89cd-4015-97d1-718779df7dfe",
  "priority": 1,
  "request": {
    "urlPattern": "/faulty.*/.*/path/path",
    "method": "POST",
    "bodyPatterns": [
      {
        "matches": ".*<xml>permissions</xml>.*"
      }
    ]
  },
  "response": {
    "status": 200,
    "bodyFileName": "staticbody.xml",
    "fixedDelayMilliseconds": 35000
  }
}`

The above stub should respond with a 200 after 35000ms, but for some reason it's responding with a 404 after 30000ms. 

If I remove the request bodyPatterns property, and only match on urlPattern/method, the fixed delay works, and I get a 200 response after 35000ms. 

Equally, if I keep the bodyPatterns property in the request, but reduce the fixed delay to 29000ms, I also get a 200 response after that period.

More Info... This issues only occurs when async response is enabled i.e. 

java -jar ./wiremock-standalone-2.19.0.jar --https-port 8443 --async-response-enabled true

**Comment by SamL1** [comment] 2018-11-01 12:13
A bit more of an updated and looking at some of the verbose tracing. I think the problem follows roughly this pattern...

1. The request hits the wiremock service.
2. Wiremock delays making the request for the fixedDelayMilliseconds period.
3. The request is disposed after 30000ms and the request body is lost.
4. The request is reissued, but it no longer matches the stub because of the missing body.
5. Wiremock returns a 404.

If a fix for this is tricky, as a workaround is there anyway we can increase the 30000ms period before the body information is lost?

**Comment by SamL1** [comment] 2018-11-02 21:06
@tomakehurst I think this might be related to the jetty idletimeout default. Can you give me any pointers to where I might set this in code, and I'll try bumping it up and see if it makes a difference.

**Comment by SamL1** [comment] 2018-11-04 22:17
I've tried raising the Jetty idleTimeout to 60000ms, and it doesn't help. What I've found is when running in async response mode, using any fixedDelay of greater than 30000ms results in a second call to StubRequestHandler.handleRequest. 

Normally this isn't much of a problem, but on the second pass the requestBody is empty, meaning any mapping using bodyPattern won't match and a 404 is returned.

I'm a bit stumped at what's triggering the second call to StubRequestHandler.handleRequest.

**Comment by tomakehurst** [comment] 2018-11-05 10:48
OK, I think I've managed to replicate this. Odd behaviour, but in the async case I think it's tripping Jetty's async timeout. This isn't exposed by WireMock at the moment (and I'm struggling to figure out where it is) but I'll probably raise it to a substantially higher value in the first instance.

**Comment by tomakehurst** [comment] 2018-11-05 10:53
Just discovered that Jetty uses a system property when setting the async timeout, so a workaround might be to set this on startup e.g.

`-Dorg.eclipse.jetty.server.HttpChannelState.DEFAULT_TIMEOUT=120000`

**Comment by tomakehurst** [comment] 2018-11-05 10:58
:point_up: I can confirm this fixes the problem for my test case

**Comment by SamL1** [comment] 2018-11-05 11:31
@tomakehurst, thanks for the update. I've tried setting this from the console before invoking wiremock i.e. java -Dorg.eclipse.jetty.server.HttpChannelState.DEFAULT_TIMEOUT = 120000, but I'm not seeing any improvement. 

I'm currently running from Windows 10.

**Comment by tomakehurst** [comment] 2018-11-05 11:34
I did this in my test case:

```java
@BeforeClass
public static void initClass() {
    System.setProperty("org.eclipse.jetty.server.HttpChannelState.DEFAULT_TIMEOUT", "120000");
}
```

**Comment by SamL1** [comment] 2018-11-05 11:40
Yes, I've set in code from the Main method. It works 👍  

It's a long time since I've done any Java development :-)

Thanks for your help.

**Comment by tomakehurst** [comment] 2018-11-05 21:08
Bumped the async timeout to 5 minutes in 72ea24aa1e4bd48852ac9229b7c29e5c23203fe1

**Closed by tomakehurst** 2018-11-05 21:08 UTC
