### ISSUE TITLE
wiremock.client.VerificationException: Expected status 2xx for http://localhost:6789/__admin/mappings but was 500

### ISSUE THREAD

**Issue by ber4444** [tomakehurst/wiremock#1323] opened 2020-06-01 16:28 UTC
# Issue guidelines

My espresso tests are all failing with the above, after introducing `coreLibraryDesugaringEnabled true` (Java 8 API support on lower Android API levels) that comes with the Android Google Plugin 4.0

## Bug reports

- [x] Which version of WireMock you're using - 
`androidTestImplementation "com.github.tomakehurst:wiremock-standalone:2.26.3"`
- [x] How you're starting and configuring WireMock, including configuration or CLI the command line
```
    @Rule
    @JvmField
    val wireMockRule = WireMockRule(wireMockConfig().port(6789), false)
wireMockRule.start()
        WireMock.stubFor(WireMock.any(WireMock.urlMatching("/$endPoint"))
                .willReturn(responseManager.getResponse(mockResponseKey)))
```
- [x] Stacktrace
```
com.github.tomakehurst.wiremock.client.VerificationException: Expected status 2xx for http://localhost:6789/__admin/mappings but was 500
at com.github.tomakehurst.wiremock.client.HttpAdminClient.safelyExecuteRequest(HttpAdminClient.java:476)
at com.github.tomakehurst.wiremock.client.HttpAdminClient.executeRequest(HttpAdminClient.java:454)
at com.github.tomakehurst.wiremock.client.HttpAdminClient.addStubMapping(HttpAdminClient.java:131)
at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:298)
at com.github.tomakehurst.wiremock.client.WireMock.register(WireMock.java:293)
at com.github.tomakehurst.wiremock.client.WireMock.givenThat(WireMock.java:104)
at com.github.tomakehurst.wiremock.client.WireMock.stubFor(WireMock.java:108)
```
- [ ] ~~A failing test case that demonstrates the problem~~
- [ ] ~~Profiler data if the issue is performance related~~

**Comment by tomakehurst** [comment] 2020-06-01 16:30
You've probably mismatched the server and DSL port numbers - that 500 is probably coming from another service you have running locally.

Don't call `wireMockRule.start()`, that's done automatically by the rule lifecycle.

**Comment by ber4444** [comment] 2020-06-02 23:06
No, the only thing I changed is adding `coreLibraryDesugaringEnabled`, the tests do pass without that. I see in the Firebase Test console a warning about `W/Java7Handlers(6175): Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added` which also confirms that the Java8 API support (which is that `coreLibraryDesugaringEnabled` does) is the issue within the `Java7Handlers` class in one of your dependencies (`wiremock.com.fasterxml.jackson.databind.ext` package).

**Comment by tomakehurst** [comment] 2020-06-03 09:00
Are you using the jre8 variant of WireMock?

And can you turn on verbose logging so you can see what's causing that 500 on the server-side?

**Comment by ber4444** [comment] 2020-06-03 17:13
jre8 doesn't work with my min sdk level (it needs api level 26) so I'm using jre7

as I mentioned, this is an issue within Jackson-databind, https://github.com/FasterXML/jackson-databind/issues/2744, meanwhile you can think about replacing Jackson with something better

**Comment by tomakehurst** [comment] 2020-06-03 17:23
Why is desugaring necessary if you're sticking with JRE7? I thought that was intended to backport JRE8+ lambdas etc.

It's highly unlikely I'll be swapping Jackson out any time soon (or at all).

**Comment by ber4444** [comment] 2020-06-03 18:21
a subset of java 8 apis are supported; I have other dependencies that remain in that subset but your jre8 artifact is outside of the supported set

**Comment by tomakehurst** [comment] 2020-06-03 18:26
I still don't understand why it's necessary to desugar the JRE7 build though?

**Comment by ber4444** [comment] 2020-06-03 18:33
You cannot "selectively" desugar and exclude a single dependency like your jre7 artifact. Desugaring is needed because I have
```
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
```
 and as you can see at https://developer.android.com/studio/write/java8-support, with min sdk < 26, you need desugaring to support the above

**Comment by tomakehurst** [comment] 2020-06-03 18:35
OK, thanks for letting me know. I'm not an Android dev, so this is useful knowledge.

I'll keep this issue open for the time being, but I'm going to wait and see what the Jackson folks say about the issue you've opened with them.

**Comment by ber4444** [comment] 2020-06-03 21:17
They say from the Jackson side it's a warning only and should not prevent normal usage.

Here is the test log where the error is happening, despite success from the backend mock:

```
06-02 22:27:25.224: D/XXXXManager(6232): Returning response for path segment: alertsCount body: {..........,"status": "SUCCESS"}
06-02 22:27:25.249: W/Java7Handlers(6232): Unable to load JDK7 types (java.nio.file.Path): no Java7 type support added
06-02 22:27:25.399: E/TestRunner(6232): failed: test8DecisionScreenWhenPartiallyApproved(com.americanexpress.receiptmatch.checkspendingpower.CheckSpendingPowerUITest)
06-02 22:27:25.399: E/TestRunner(6232): ----- begin exception -----
06-02 22:27:25.401: E/TestRunner(6232): com.github.tomakehurst.wiremock.client.VerificationException: Expected status 2xx for http://localhost:6789/__admin/mappings but was 500
```

**Comment by yogurtearl** [comment] 2020-06-08 21:58
Looks like Android Gradle Plugin doesn't "desugar" `java.nio.file.Path` yet...   
Not listed here:
https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring

**Comment by yogurtearl** [comment] 2020-06-08 22:17
Filed with Android tools team: https://issuetracker.google.com/issues/158452385

**Comment by tomakehurst** [comment] 2021-04-29 11:13
Closing, as I don't think there's anything more we can do here until the desugaring issue is resolved.

**Closed by tomakehurst** 2021-04-29 11:13 UTC
